[package]
name = "attestation"
version = "0.0.0"
authors = ["sasurobert <robert.sasu@elrond.com>", "andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[features]
wasm-output-mode = ["elrond-wasm-node"]

[dependencies.elrond-wasm]
version = "0.9.2"

[dependencies.elrond-wasm-derive]
version = "0.9.2"

[dependencies.elrond-wasm-node]
version = "0.9.2"
optional = true
features = ["small-int-ei"]

[dev-dependencies.elrond-wasm-debug]
version = "0.9.2"
